Completed css-canvas-medical
GiancarloMassoni/c1022-code-solutions pull request #21
Opened 2022-10-16 04:31 UTC by GiancarloMassoni

![Screen Shot 2022-10-15 at 9 22 57 PM](https://user-images.githubusercontent.com/71737839/196018163-cc0ed7f8-27a9-4f20-a174-876864afe74a.png)

![Screen Shot 2022-10-15 at 9 23 09 PM](https://user-images.githubusercontent.com/71737839/196018175-4e8ec39c-fcee-4511-8d72-26b993d05d7b.png)

2022-10-16 04:32 UTC, GiancarloMassoni commented
wrong top picture uploaded. 

![Screen Shot 2022-10-15 at 9 32 19 PM](https://user-images.githubusercontent.com/71737839/196018260-d19207b4-0f00-4447-b99e-1099e19ae75b.png)

2022-10-17 20:55 UTC, codingcodymiller requested changes

2022-10-17 20:55 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-header">
`column-` classes should be named after their size, not their content. You want them to be reusable. This class is now not reusable outside the header.

2022-10-17 20:55 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-half-spacing">
instead of `column-half-spacing`, use `column-half` and make a second class to handle whatever spacing you are doing.

2022-10-17 20:55 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-two-thirds-footer white-text">
Again, `column-two-thirds`, not `column-two-thirds-footer`

2022-10-17 20:55 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-half-spacing">
Same note here.

2022-10-17 20:55 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
The only valid property applied to a `column-` class is `flex-basis`. Everything else belongs on a separate class that you can add to the element in addition to the `column-` layout class. This issue is present in multiple other places in your CSS as well, please make sure you address it wherever it is happening.

2022-10-19 16:25 UTC, codingcodymiller approved these changes
Great work!

2022-10-19 16:53 UTC, merged